version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka-brokers:
    image: mjnacht/kafka-brokers
    ports: 
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka-brokers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-file-producers:
    image: mjnacht/kafka-file-producers
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka-file-producers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-web-producers:
    image: mjnacht/kafka-web-producers
    ports:
      - "80:80"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka-web-producers
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  master:
    image: mjnacht/spark-master
    command: start-spark master
    hostname: master
    ports:
      - "6066:6066"
      - "7070:7070"
      - "8080:8080"
      - "50070:50070"

  worker:
    image: singularities/spark
    command: start-spark worker master
    ports:
      - "8081:8081"
    environment:
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2g
    links:
      - master
